# -*- coding: utf-8 -*-
"""Deepfake_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T9oc5rj5fb_8lSKrYOuiyQvr60q2_cyc
"""

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0))

!pip install transformers==4.37.0 facenet-pytorch scipy -q

!pip install --quiet --upgrade torch torchvision torchaudio

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.models as models
import numpy as np
import os
import json
import random

from torch.utils.data import Dataset, DataLoader
from transformers import Wav2Vec2Model
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, confusion_matrix

import torch
import torchvision

print(torch.__version__)
print(torchvision.__version__)

DATA_DIR = "/content/drive/MyDrive/deepfake_data/processed"
SPLIT_PATH = "/content/drive/MyDrive/deepfake_data/splits.json"

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Using device:", device)

from google.colab import drive
drive.mount('/content/drive')

import os
print(os.listdir("/content/drive/MyDrive/"))

DATA_DIR = "/content/drive/MyDrive/deepfake_data/processed"
SPLIT_PATH = "/content/drive/MyDrive/deepfake_data/splits.json"

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print("Using device:", device)

with open(SPLIT_PATH) as f:
    split_data = json.load(f)

train_files = split_data['train_files']
train_labels = split_data['train_labels']
val_files = split_data['val_files']
val_labels = split_data['val_labels']
test_files = split_data['test_files']
test_labels = split_data['test_labels']

print("Train:", len(train_files), "Val:", len(val_files), "Test:", len(test_files))

class DeepfakeDataset(Dataset):
    def __init__(self, files, labels, audio_condition='clean'):
        self.samples = []
        for f, l in zip(files, labels):
            name = f.replace('.mp4', '')
            audio_path = f'{DATA_DIR}/audio/{name}.pt'
            frames_path = f'{DATA_DIR}/frames/{name}.pt'
            if os.path.exists(audio_path) and os.path.exists(frames_path):
                self.samples.append((name, l))

        self.audio_condition = audio_condition
        print(f"Dataset: {len(self.samples)} samples | condition: {audio_condition}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        name, label = self.samples[idx]

        # ---- Frames ----
        frames = torch.load(f'{DATA_DIR}/frames/{name}.pt')
        frames = frames.float() / 255.0

        if frames.shape[0] < 4:
            pad = torch.zeros(4 - frames.shape[0], *frames.shape[1:])
            frames = torch.cat([frames, pad], dim=0)
        else:
            frames = frames[:4]

        # ---- Audio ----
        audio = torch.load(f'{DATA_DIR}/audio/{name}.pt')

        target_len = 48000
        if audio.shape[1] >= target_len:
            audio = audio[:, :target_len]
        else:
            pad = torch.zeros(1, target_len - audio.shape[1])
            audio = torch.cat([audio, pad], dim=1)

        # Normalize audio
        audio = audio / (audio.abs().max() + 1e-8)

        condition = self.audio_condition

        # ---- Mixed training ----
        if condition == 'mixed':
            choice = random.choice(['clean', 'noisy', 'missing'])

            if choice == 'noisy':
                noise = torch.randn_like(audio) * 1.0
                audio = audio + noise

            elif choice == 'missing':
                audio = torch.zeros_like(audio) + 1e-6

        elif condition == 'noisy':
            noise = torch.randn_like(audio) * 1.0
            audio = audio + noise

        elif condition == 'missing':
            audio = torch.zeros_like(audio) + 1e-6

        return frames, audio, torch.tensor(label, dtype=torch.float32)

train_dataset = DeepfakeDataset(train_files, train_labels, 'mixed')
val_dataset   = DeepfakeDataset(val_files, val_labels, 'clean')

train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
val_loader   = DataLoader(val_dataset, batch_size=4, shuffle=False)

class DeepfakeDetector(nn.Module):
    def __init__(self):
        super().__init__()

        # ---- Visual ----
        mobilenet = models.mobilenet_v2(weights='DEFAULT')
        self.visual_encoder = nn.Sequential(*list(mobilenet.children())[:-1])
        self.visual_pool = nn.AdaptiveAvgPool2d((1, 1))
        self.visual_proj = nn.Linear(1280, 256)

        # ---- Audio ----
        self.audio_encoder = Wav2Vec2Model.from_pretrained("facebook/wav2vec2-base")

        # Freeze audio encoder
        for param in self.audio_encoder.parameters():
            param.requires_grad = False

        self.audio_proj = nn.Linear(768, 256)

        # NEW GATE (512 input)
        self.gate = nn.Sequential(
            nn.Linear(512, 64),
            nn.ReLU(),
            nn.Linear(64, 1),
            nn.Sigmoid()
        )

        # ---- Classifier ----
        self.classifier = nn.Sequential(
            nn.Linear(512, 128),
            nn.ReLU(),
            nn.Dropout(0.3),
            nn.Linear(128, 1)
        )

    def forward(self, frames, audio):
        B, T, C, H, W = frames.shape

        # ---- Visual features ----
        frames = frames.view(B*T, C, H, W)
        vis_feat = self.visual_encoder(frames)
        vis_feat = self.visual_pool(vis_feat)
        vis_feat = vis_feat.view(B, T, -1).mean(dim=1)
        vis_feat = self.visual_proj(vis_feat)

        # ---- Audio features ----
        audio = audio.squeeze(1)
        audio_out = self.audio_encoder(audio).last_hidden_state.mean(dim=1)
        aud_feat = self.audio_proj(audio_out)

        # Gate uses BOTH modalities
        gate_input = torch.cat([vis_feat, aud_feat], dim=1)
        gate = self.gate(gate_input)

        # Strong fusion
        fused_audio = gate * aud_feat
        fused_visual = (1 - gate) * vis_feat
        fused = torch.cat([fused_visual, fused_audio], dim=1)

        # ---- Output ----
        out = self.classifier(fused).squeeze(1)
        return out, gate

model = DeepfakeDetector().to(device)

criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([1.5]).to(device))
optimizer = optim.Adam(model.parameters(), lr=1e-4)

best_val = 0

for epoch in range(10):
    model.train()

    for frames, audio, labels in train_loader:
        frames = frames.to(device)
        audio = audio.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        preds, gate = model(frames, audio)

        classification_loss = criterion(preds, labels)
        gate_loss = torch.mean((gate - 0.5) ** 2)

        loss = classification_loss + 0.3 * gate_loss

        loss.backward()
        optimizer.step()

    model.eval()
    all_preds, all_labels = [], []
    gates = []

    with torch.no_grad():
        for frames, audio, labels in val_loader:
            frames = frames.to(device)
            audio = audio.to(device)

            preds, gate = model(frames, audio)

            gates.append(gate.mean().item())

            probs = torch.sigmoid(preds)

            all_preds.extend((probs > 0.5).cpu().numpy())
            all_labels.extend(labels.numpy())

    acc = accuracy_score(all_labels, all_preds)

    print(f"Epoch {epoch+1}")
    print(f"Val Accuracy: {acc:.4f}")
    print(f"Avg Gate Value: {sum(gates)/len(gates):.4f}")

    if acc > best_val:
        best_val = acc
        torch.save(model.state_dict(), "/content/drive/MyDrive/deepfake_data/best_model.pt")
        print("Model saved")

torch.save(model.state_dict(), "/content/drive/MyDrive/deepfake_data/best_model.pt")
print("Model saved manually")

import os
print(os.listdir("/content/drive/MyDrive/deepfake_data"))

from sklearn.metrics import roc_curve, accuracy_score, precision_score, recall_score, f1_score, roc_auc_score
import matplotlib.pyplot as plt
import numpy as np
import torch
from torch.utils.data import DataLoader

def get_optimal_threshold(model, val_loader, device):
    model.eval()
    all_probs, all_labels = [], []
    with torch.no_grad():
        for frames, audio, labels in val_loader:
            frames, audio = frames.to(device), audio.to(device)
            preds, _ = model(frames, audio)
            probs = torch.sigmoid(preds)
            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    fpr, tpr, thresholds = roc_curve(all_labels, all_probs)
    j_scores = tpr - fpr
    best_threshold = thresholds[np.argmax(j_scores)]
    return best_threshold


def test_model(condition, threshold):
    print(f"Testing Condition: {condition} (Threshold: {threshold:.4f})")

    test_ds = DeepfakeDataset(test_files, test_labels, audio_condition=condition)
    test_loader = DataLoader(test_ds, batch_size=4, shuffle=False)

    model.eval()
    all_probs, all_labels = [], []

    with torch.no_grad():
        for frames, audio, labels in test_loader:
            frames, audio = frames.to(device), audio.to(device)
            preds, _ = model(frames, audio)
            probs = torch.sigmoid(preds)
            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    all_probs = np.array(all_probs)
    all_labels = np.array(all_labels)
    all_preds = (all_probs > threshold).astype(int)

    metrics = {
        "acc": accuracy_score(all_labels, all_preds),
        "prec": precision_score(all_labels, all_preds, zero_division=0),
        "rec": recall_score(all_labels, all_preds, zero_division=0),
        "f1": f1_score(all_labels, all_preds, zero_division=0),
        "auc": roc_auc_score(all_labels, all_probs)
    }

    print(f"Accuracy: {metrics['acc']:.4f}, Precision: {metrics['prec']:.4f}, "
          f"Recall: {metrics['rec']:.4f}, F1: {metrics['f1']:.4f}, AUC: {metrics['auc']:.4f}")
    print("-" * 30)
    return metrics


def visualize_gate_behavior(model, device):
    conditions = ['clean', 'noisy', 'missing']
    avg_gates = []

    for cond in conditions:
        ds = DeepfakeDataset(test_files, test_labels, audio_condition=cond)
        loader = DataLoader(ds, batch_size=4)
        gates = []
        with torch.no_grad():
            for frames, audio, _ in loader:
                frames, audio = frames.to(device), audio.to(device)
                _, gate = model(frames, audio)
                gates.extend(gate.cpu().numpy())
        avg_gates.append(np.mean(gates))

    plt.figure(figsize=(8, 5))
    plt.bar(conditions, avg_gates)
    plt.ylabel('Average Gate Weight (Audio Importance)')
    plt.title('Gating Mechanism Behavior')
    plt.ylim(0, 1)
    plt.show()


threshold = get_optimal_threshold(model, val_loader, device)
print("Best Threshold:", threshold)

results = {
    'clean': test_model('clean', threshold),
    'noisy': test_model('noisy', threshold),
    'missing': test_model('missing', threshold)
}

visualize_gate_behavior(model, device)

val_threshold = 0.5
print(f"Using Threshold: {val_threshold}")

clean   = test_model('clean', val_threshold)
noisy   = test_model('noisy', val_threshold)
missing = test_model('missing', val_threshold)

baseline_model = BaselineDetector(model.audio_encoder).to(device)

criterion = nn.BCEWithLogitsLoss(pos_weight=torch.tensor([1.5]).to(device))
optimizer = torch.optim.Adam(baseline_model.parameters(), lr=1e-4)

baseline_model.train()

for epoch in range(5):
    for frames, audio, labels in train_loader:
        frames = frames.to(device)
        audio = audio.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()
        preds = baseline_model(frames, audio)
        loss = criterion(preds, labels)
        loss.backward()
        optimizer.step()

    print(f"Baseline Epoch {epoch+1} done")

def test_baseline(condition, threshold):
    print(f"Testing Baseline - Condition: {condition}")

    test_ds = DeepfakeDataset(test_files, test_labels, audio_condition=condition)
    test_loader = DataLoader(test_ds, batch_size=4, shuffle=False)

    baseline_model.eval()
    all_probs, all_labels = [], []

    with torch.no_grad():
        for frames, audio, labels in test_loader:
            frames = frames.to(device)
            audio = audio.to(device)

            preds = baseline_model(frames, audio)
            probs = torch.sigmoid(preds)

            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    all_probs = np.array(all_probs)
    all_labels = np.array(all_labels)
    all_preds = (all_probs > threshold).astype(int)

    acc = accuracy_score(all_labels, all_preds)
    auc = roc_auc_score(all_labels, all_probs)

    print(f"Baseline -> Acc: {acc:.4f}, AUC: {auc:.4f}")
    print("-" * 30)

    return {"acc": acc, "auc": auc}

val_threshold = 0.5

b_clean   = test_baseline('clean', val_threshold)
b_noisy   = test_baseline('noisy', val_threshold)
b_missing = test_baseline('missing', val_threshold)

proposed_acc = [
    clean['acc'],
    noisy['acc'],
    missing['acc']
]

baseline_acc = [
    b_clean['acc'],
    b_noisy['acc'],
    b_missing['acc']
]

labels = ['Clean', 'Noisy', 'Missing']
x = np.arange(len(labels))
width = 0.35

plt.figure(figsize=(10, 6))
plt.bar(x - width/2, baseline_acc, width, label='Baseline (Static Fusion)')
plt.bar(x + width/2, proposed_acc, width, label='Proposed (Adaptive Gating)')

plt.ylabel('Accuracy')
plt.title('Performance Comparison under Audio Degradation')
plt.xticks(x, labels)
plt.legend()
plt.ylim(0, 1)
plt.grid(axis='y', alpha=0.3)
plt.show()

import pandas as pd

data = {
    "Condition": ["Clean", "Noisy", "Missing"],
    "Accuracy": [clean['acc'], noisy['acc'], missing['acc']],
    "Precision": [clean['prec'], noisy['prec'], missing['prec']],
    "Recall": [clean['rec'], noisy['rec'], missing['rec']],
    "F1": [clean['f1'], noisy['f1'], missing['f1']],
    "AUC": [clean['auc'], noisy['auc'], missing['auc']]
}

df = pd.DataFrame(data)
print(df)

from sklearn.metrics import confusion_matrix
import seaborn as sns

def plot_confusion(condition):
    test_ds = DeepfakeDataset(test_files, test_labels, audio_condition=condition)
    loader = DataLoader(test_ds, batch_size=4)

    all_preds, all_labels = [], []

    with torch.no_grad():
        for frames, audio, labels in loader:
            frames, audio = frames.to(device), audio.to(device)
            preds, _ = model(frames, audio)
            probs = torch.sigmoid(preds)

            all_preds.extend((probs > 0.5).cpu().numpy())
            all_labels.extend(labels.numpy())

    cm = confusion_matrix(all_labels, all_preds)

    plt.figure(figsize=(5,4))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
    plt.title(f'Confusion Matrix - {condition}')
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.show()

plot_confusion('clean')

def plot_gate_distribution():
    conditions = ['clean', 'noisy', 'missing']

    plt.figure(figsize=(8,5))

    for cond in conditions:
        ds = DeepfakeDataset(test_files, test_labels, audio_condition=cond)
        loader = DataLoader(ds, batch_size=4)

        gates = []

        with torch.no_grad():
            for frames, audio, _ in loader:
                frames = frames.to(device)
                audio = audio.to(device)

                _, gate = model(frames, audio)

                gates.extend(gate.cpu().numpy().flatten())  # 🔥 important fix

        if len(gates) > 0:
            plt.hist(gates, bins=20, alpha=0.5, label=cond)

    plt.xlabel("Gate Value")
    plt.ylabel("Frequency")
    plt.title("Gate Distribution Across Conditions")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.show()

plot_gate_distribution()

labels = ['Clean', 'Noisy', 'Missing']

precision = [clean['prec'], noisy['prec'], missing['prec']]
recall = [clean['rec'], noisy['rec'], missing['rec']]

x = np.arange(len(labels))
width = 0.35

plt.figure(figsize=(8,5))
plt.bar(x - width/2, precision, width, label='Precision')
plt.bar(x + width/2, recall, width, label='Recall')

plt.xticks(x, labels)
plt.ylabel('Score')
plt.title('Precision vs Recall Across Conditions')
plt.legend()
plt.ylim(0,1)
plt.show()

def plot_roc(condition):
    test_ds = DeepfakeDataset(test_files, test_labels, audio_condition=condition)
    loader = DataLoader(test_ds, batch_size=4)

    all_probs, all_labels = [], []

    with torch.no_grad():
        for frames, audio, labels in loader:
            frames, audio = frames.to(device), audio.to(device)
            preds, _ = model(frames, audio)
            probs = torch.sigmoid(preds)

            all_probs.extend(probs.cpu().numpy())
            all_labels.extend(labels.numpy())

    fpr, tpr, _ = roc_curve(all_labels, all_probs)

    plt.plot(fpr, tpr, label=condition)

plt.figure()
plot_roc('clean')
plt.plot([0,1],[0,1],'--')
plt.xlabel('FPR')
plt.ylabel('TPR')
plt.title('ROC Curve')
plt.legend()
plt.show()

torch.save(model.state_dict(), "/content/drive/MyDrive/deepfake_data/best_model.pt")

import os
import json
import matplotlib.pyplot as plt

save_dir = "/content/drive/MyDrive/deepfake_results"
os.makedirs(save_dir, exist_ok=True)

#Save model
torch.save(model.state_dict(), f"{save_dir}/best_model.pt")

#Save metrics
results_dict = {
    "clean": clean,
    "noisy": noisy,
    "missing": missing
}

with open(f"{save_dir}/metrics.json", "w") as f:
    json.dump(results_dict, f, indent=4)

#Save comparison plot
plt.figure(figsize=(10,6))
plt.bar(x - width/2, baseline_acc, width, label='Baseline')
plt.bar(x + width/2, proposed_acc, width, label='Proposed')
plt.legend()
plt.title("Performance Comparison")
plt.savefig(f"{save_dir}/comparison.png", bbox_inches='tight')
plt.close()

#Save gate distribution (rerun plotting quickly)
plot_gate_distribution()
plt.savefig(f"{save_dir}/gate_distribution.png", bbox_inches='tight')
plt.close()

#Save ROC (clean)
plot_roc('clean')
plt.savefig(f"{save_dir}/roc_curve.png", bbox_inches='tight')
plt.close()

#confusion matrix
plot_confusion('clean')
plt.savefig(f"{save_dir}/confusion_matrix.png", bbox_inches='tight')
plt.close()

print("✅ All files saved in:", save_dir)